// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeCast.Infrastructure;

#nullable disable

namespace WeCast.Infrastructure.Migrations
{
    [DbContext(typeof(WeCastDbContext))]
    partial class WeCastDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeCast.Domain.Entities.HourlyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Temperature2m")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeatherDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeatherDataId");

                    b.ToTable("Hourly");
                });

            modelBuilder.Entity("WeCast.Domain.Entities.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Elevation")
                        .HasColumnType("int");

                    b.Property<double>("GenerationtimeMs")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimezoneAbbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtcOffsetSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });

            modelBuilder.Entity("WeCast.Domain.Entities.HourlyData", b =>
                {
                    b.HasOne("WeCast.Domain.Entities.WeatherData", "WeatherData")
                        .WithMany("Hourly")
                        .HasForeignKey("WeatherDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherData");
                });

            modelBuilder.Entity("WeCast.Domain.Entities.WeatherData", b =>
                {
                    b.OwnsOne("WeCast.Domain.Entities.HourlyUnit", "HourlyUnits", b1 =>
                        {
                            b1.Property<int>("WeatherDataId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Temperature2m")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Time")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WeatherDataId");

                            b1.ToTable("HourlyUnits");

                            b1.WithOwner()
                                .HasForeignKey("WeatherDataId");
                        });

                    b.Navigation("HourlyUnits");
                });

            modelBuilder.Entity("WeCast.Domain.Entities.WeatherData", b =>
                {
                    b.Navigation("Hourly");
                });
#pragma warning restore 612, 618
        }
    }
}
